== Development

The `jooby run` tool allows to restart your application on code changes without exiting the JVM.

This feature is also known as hot reload/swap. Makes you feel like coding against a script 
language where you modify your code and changes are visible immediately.
  
The tool uses the https://jboss-modules.github.io/jboss-modules/manual[JBoss Modules] library
that effectively reload application classes.

For now `jooby run` is available as Maven and Gradle plugins.

=== Usage

1) Add build plugin:

.pom.xml
[source, xml, role = "primary", subs="verbatim,attributes"]
----
<plugins>
  ...
  <plugin>
    <groupId>io.jooby</groupId>
    <artifactId>jooby-maven-plugin</artifactId>
    <version>{joobyVersion}</version>
  </plugin>
  ...
</plugins>
----

.build.gradle
[source, gradle, role = "secondary", subs="verbatim,attributes"]
----
buildscript {
  ext {
    joobyVersion = "{joobyVersion}"
  }
}

plugins {
  id "application"
  id "io.jooby.run" version "{joobyVersion}"
}
----

2) Set main class

.pom.xml
[source, xml, role = "primary"]
----
<properties>
  <application.class>myapp.App</application.class>
</properties>
----

.build.gradle
[source, gradle, role = "secondary"]
----
mainClassName = "myapp.App"
----

3) Run application

.Maven
[source, bash, role = "primary"]
----
mvn jooby:run
----

.Gradle
[source, bash, role = "secondary"]
----
./gradlew joobyRun
----

=== Compilation & Restart

Changing a `java` or `kt` file triggers a compilation request. Compilation is executed by
Maven/Gradle using an incremental build process.

If compilation succeed, application is restarted.

Compilation errors are printed to the console by Maven/Gradle.

Changing a `.conf`, `.properties` file triggers just an application restart request. They don't trigger
a compilation request.

Compiler is enabled by default, except for Eclipse users. Plugin checks for `.classpath` file in
project directory, when found plugin compiler is OFF and let Eclipse compiles the code. 

=== Options

The next example shows all the available options with their default values:

.pom.xml
[source, xml, role = "primary", subs="verbatim,attributes"]
----
<plugins>
  ...
  <plugin>
    <groupId>io.jooby</groupId>
    <artifactId>jooby-maven-plugin</artifactId>
    <version>{joobyVersion}</version>
    <configuration>
      <mainClass>${application.class}</mainClass>                  <1>
      <restartExtensions>conf,properties,class</restartExtensions> <2>
      <compileExtensions>java,kt</compileExtensions>               <3>
      <port>8080</port>                                            <4>
      <waitTimeBeforeRestart>500</waitTimeBeforeRestart>           <5>
      <useSingleClassLoader>false</useSingleClassLoader>           <6>
    </configuration>
  </plugin>
  ...
</plugins>
----

.build.gradle
[source, gradle, role = "secondary", subs="verbatim,attributes"]
----
buildscript {
  ext {
    joobyVersion = "{joobyVersion}"
  }
}

plugins {
  id "application"
  id "io.jooby.run" version "{joobyVersion}"
}

joobyRun {
  mainClassName = "${mainClassName}"                               <1>
  restartExtensions = ["conf", "properties", "class"]              <2>
  compileExtensions = ["java", "kt"]                               <3>
  port = 8080                                                      <4>
  waitTimeBeforeRestart = 500                                      <5>
  useSingleClassLoader = false                                     <6>
}
----

<1> Application main class
<2> Restart extensions. A change on these files trigger a restart request.
<3> Source extensions. A change on these files trigger a compilation request, followed by a restart request.
<4> Application port
<5> How long to wait after last file change to restart. Default is: `500` milliseconds.
<5> Use a single/fat class loader to run your application. This is required on complex project classpath where you start seeing weird reflection errors. This was the default mode in Jooby 2.x. The new model since 3.x uses a modular classloader which improves restart times and memory usage making it faster. Default is: `false`.

For Maven and Gradle there are two variant `mvn jooby:testRun` and `./gradlew joobyTestRun` they work
by expanding the classpath to uses the `test` scope or source set.
