== Extensions and Services

Jooby comes with a simple extension mechanism. The javadoc:Extension[] API allows to configure
, extend an application by adding shared/single services, infrastructure/technical concerns like 
dependency injection, database connection pools, cron-job, etc.

Services are shared/singleton objects, usually with a clear lifecycle for starting and stopping them.

=== Writing Custom Extension

We are going to develop a custom extension that configure a `DataSource` service.

.Java
[source, java, role = "primary"]
----
import io.jooby.Extension;

public class MyExtension implements Extension {
   
   public void install(Jooby application) {
      DataSource dataSource = createDataSource();           <1>

      ServiceRegistry registry = application.getServices(); <2>
      registry.put(MyDataSource.class, dataSource);         <3>

      application.onStop(dataSource::close)                 <4>
   }
}
----

.Kotlin
[source, kotlin, role = "secondary"]
----
import io.jooby.Extension

class MyExtension: Extension {
  override fun install(application: Jooby) {
    val dataSource = createDataSource()                     <1>

    val registry = application.services                     <2>
    registry.put(MyDataSource::class, dataSource)           <3>
    application.onStop(dataSource::close)                   <4>
  }
}
----

<1> Create the service (DataSource)
<2> Access to the service registry
<3> Save into the service registry
<4> Close/release service on application stop

Let's install the extension and use the service!!

 
.Java
[source, java, role = "primary"]
----
public class App extends Jooby {
   
   {
     install(new MyExtension());                      <1>
     
     get("/", ctx -> {
       MyDataSource ds = require(MyDataSource.class); <2>
       // ...
     });
   }
}
----

.Kotlin
[source, kotlin, role = "secondary"]
----
import io.jooby.Extension

class App: Kooby({

  install(MyExtension())                              <1>

  get("/") {
    val ds = require(MyDataSource::class)             <2>
  }
})
----
 
<1> Install the extension
<2> Use the service

=== Collection of Services

Adding a collection to the service registry is supported too.

.List/Set
[source,java]
----
import io.jooby.Extension;import io.jooby.Reified;

public class Cats implements Extension {
   
   public void install(Jooby application) {
      ServiceRegistry registry = application.getServices();
      // as list
      registry.listOf(Animal.class).add(new Cat());
      // as set
      registry.setOf(Animal.class).add(new Cat());
      // as map
      registry.mapOf(String.class, Animal.class).put("cat", new Cat());
   }
}

public class Dogs implements Extension {
   
   public void install(Jooby application) {
      ServiceRegistry registry = application.getServices();
      // as list
      registry.listOf(Animal.class).add(new Dog());
      // as set
      registry.setOf(Animal.class).add(new Dog());
      // as map
      registry.mapOf(String.class, Animal.class).put("dog", new Dog());
   }
}

{
  install(new Cats());
  install(new Dogs());
  // as list
  get("/list", ctx -> {
    return ctx.require(Reified.list(Animal.class));
  });
  // as set
  get("/set", ctx -> {
    return ctx.require(Reified.set(Animal.class));
  });
  // as map
  get("/map", ctx -> {
    return ctx.require(Reified.map(String.class, Animal.class));
  });
}
----

Services are accessible via javadoc:Registry[require, java.lang.Class] and integrated with
dependency injection frameworks provided by Jooby like Guice and Avaje Inject. This mean they are
accessible using the `jakarta.inject.Inject` annotation.

In addition to services, an extension module may provides infrastructure routes, body decoder/encoder,
template engines, etc.

The extension mechanism is a simple way of reusing code and decoupling technical features from
business logic.

More advanced techniques are described in the next section.
