== Modules

Modules are a key concept for building reusable and configurable pieces of software.

Modules (unlike in other frameworks) are thin and do a lot of work to bootstrap and configure an 
external library, but they DO NOT provide a new level of abstraction nor [do] they provide a custom
API to access functionality in that library. Instead they expose the library components as they are.

Modules are distributed as separated jar/dependency and usually implement the javadoc:Extension[] API.

In general they provide a `builder` class to create the and configure the external library from 
configuration properties.

Available modules are listed next.

=== Data
   * link:modules/flyway[Flyway]: Flyway migration module.
   * link:modules/hikari[HikariCP]: A high-performance JDBC connection pool.
   * link:modules/hibernate[Hibernate]: Hibernate ORM module.
   * link:modules/jdbi[Jdbi]: Jdbi module.

=== JSON
   * link:modules/jackson[Jackson]: Jackson module for Jooby.

=== Template Engine
   * link:modules/handlebars[Handlebars]: Handlebars templates for Jooby.
   * link:modules/freemarker[Freemarker]: Freemarker templates for Jooby.
   * link:modules/pebble[Pebble]: Pebble templates for Jooby.
   * link:modules/rocker[Rocker]: Rocker templates for Jooby.

.
