== Static Files

Static files are available via javadoc:Router[assets, java.lang.String] route. The `assets` route
supports classpath and file-system resources.

.Classpath resources:
[source, java, role="primary"]
----
{
  assets("/static/*", "/source"); <1>
}
----

.Kotlin
[source, kotlin, role="secondary"]
----
{
  assets("/static/*", "/source")  <1>
}
----

<1> Map all the incoming request starting with `/static/` to the `/source` classpath or file system location.

- GET `/static/index.html`     => `/source/index.html`
- GET `/static/js/file.js`     => `/source/js/file.js`
- GET `/static/css/styles.css` => `/source/css/styles.css`

The `/source` is resolved against the file system by prepending the `user.dir` path when exists
it favors the file system source, otherwise the `/source` directory must be present on classpath.

.File system resources:
[source, java, role="primary"]
----
{
  assets("/static/*", Paths.get("www")); <1>
}
----

.Kotlin
[source, kotlin, role="secondary"]
----
{
  assets("/static/*", Paths.get("www"))  <1>
}
----

<1> Map all the incoming request starting with `/static/` to a file system directory `www`

- GET `/static/index.html`     => `www/index.html`
- GET `/static/js/file.js`     => `www/js/file.js`
- GET `/static/css/styles.css` => `www/css/styles.css`

Individual file mapping is supported too:

.Classpath:
[source, role="primary"]
----
{
  assets("/myfile.js", "/static/myfile.js");
}
----

.File system
[source, role="secondary"]
----
{
  Path basedir = ...;
  assets("/myfile.js", basedire.resolve("/myfile.js"));
}
----

=== Static Site

The `assets` route works for static sites too. Just need to use a special path mapping:
 
.Classpath resources:
[source, java, role="primary"]
----
{
  Path docs = Paths.get("docs"); <1>
  assets("/docs/?*", docs);      <2>
}
----

.Kotlin
[source, kotlin, role="secondary"]
----
{
  val docs = Paths.get("docs")   <1>
  assets("/docs/?*", docs)       <2>
}
----

<1> Serve from `docs` directory
<2> Use the `/?*` mapping

The key difference is the `/?*` mapping. This mapping add support for base root mapping:

- GET `/docs`            => `/docs/index.html`
- GET `/docs/index.html` => `/docs/index.html`
- GET `/docs/about.html` => `/docs/about.html`
- GET `/docs/note`        => `/docs/note/index.html`

=== SPAs

The `assets` route works for single page applications (SPAs) too. Just need to use a special path mapping plus a fallback asset:
 
.Classpath resources:
[source, java, role="primary"]
----
{
  AssetSource docs = AssetSource.create(Paths.get("docs")); <1>
  assets("/docs/?*", new AssetHandler("index.html", docs)); <2>
}
----

.Kotlin
[source, kotlin, role="secondary"]
----
{
  val docs = AssetSource.create(Paths.get("docs"))          <1>
  assets("/docs/?*", AssetHandler("index.html", docs))      <2>
}
----

<1> Serve from `docs` directory
<2> Use the `/?*` mapping and uses `index.html` as fallback asset

SPAs mode never generates a `NOT FOUND (404)` response, unresolved assets fallback to `index.html`

=== Options

The javadoc:AssetHandler[] automatically handles `E-Tag` and `Last-Modified` headers. You can
control these headers programmatically:

.Asset handler options:
[source, java, role="primary"]
----
{
  assets("/static/*", Paths.get("www"))
    .setLastModified(false)
    .setEtag(false);
}
----

.Kotlin
[source, kotlin, role="secondary"]
----
{
  assets("/static/*", Paths.get("www"))
    .setLastModified(false)
    .setEtag(false)
}
----

The `maxAge` option set a `Cache-Control` header:

.Cache control:
[source, java, role="primary"]
----
{
  assets("/static/*", Paths.get("www"))
    .setMaxAge(Duration.ofDays(365))
}
----

.Kotlin
[source, kotlin, role="secondary"]
----
{
  assets("/static/*", Paths.get("www"))
    .setMaxAge(Duration.ofDays(365))
}
----

There is also a javadoc:AssetHandler[setNoCache] method that explicitly forbids web browsers
to cache assets.

You can use different cache configurations for different assets based on asset name if you
specify a function via javadoc:AssetHandler[cacheControl, java.util.Function]:

.Per-asset cache control:
[source, java, role="primary"]
----
{
  assets("/static/*", Paths.get("www"))
      .cacheControl(path -> {
        if (path.endsWith("dont-cache-me.html")) {
          return CacheControl.noCache(); // disable caching
        } else if (path.equals("foo.js")) {
          return CacheControl.defaults()
              .setETag(false)
              .setMaxAge(Duration.ofDays(365));
        } else {
          return CacheControl.defaults(); // AssetHandler defaults
        }
      });
}
----

.Kotlin
[source, kotlin, role="secondary"]
----
{
  assets("/static/*", Paths.get("www"))
      .cacheControl {
        when {
          it.endsWith("dont-cache-me.html") -> CacheControl.noCache() // disable caching
          it == "foo.js" -> CacheControl.defaults()
              .setETag(false)
              .setMaxAge(Duration.ofDays(365))
          else -> CacheControl.defaults() // AssetHandler defaults
        }
      }
}
----

The asset handler generates a `404` response code when requested path is not found. You can change this by throwing
an exception or generating any other content you want:


.Custom not found:
[source, java, role="primary"]
----
{
  assets("/static/*", Paths.get("www"))
      .notFound(ctx -> {
        throw new MyAssetException();
      });

  error(MyAssetException.class, (ctx, cause, code) -> {
    // render MyAssetException as you want
  });
}
----

.Kotlin
[source, kotlin, role="secondary"]
----
{
  assets("/static/*", Paths.get("www"))
    .notFound { _ ->
        throw MyAssetException()
    }
  error(MyAssetException::class) {
    // render MyAssetException as you want
  }
}
----
