/*
 * Jooby https://jooby.io
 * Apache License Version 2.0 https://jooby.io/LICENSE.txt
 * Copyright 2014 Edgar Espina
 */
package io.jooby.mcp;

import java.util.List;

import edu.umd.cs.findbugs.annotations.Nullable;
import io.jooby.Jooby;
import io.modelcontextprotocol.server.McpServerFeatures;
import io.modelcontextprotocol.server.McpStatelessServerFeatures;
import io.modelcontextprotocol.server.McpStatelessSyncServer;
import io.modelcontextprotocol.server.McpSyncServer;
import io.modelcontextprotocol.spec.McpSchema;

/** High-performance dispatcher interface generated by the Jooby APT for MCP endpoints. */
public interface McpService {

  void install(Jooby application, McpSyncServer server) throws Exception;

  void install(Jooby application, McpStatelessSyncServer server) throws Exception;

  void capabilities(McpSchema.ServerCapabilities.Builder capabilities);

  List<McpServerFeatures.SyncCompletionSpecification> completions();

  List<McpStatelessServerFeatures.SyncCompletionSpecification> statelessCompletions();

  @Nullable String serverName();
}
