/*
 * Jooby https://jooby.io
 * Apache License Version 2.0 https://jooby.io/LICENSE.txt
 * Copyright 2014 Edgar Espina
 */
package io.jooby.mcp;

import java.util.Map;

import io.modelcontextprotocol.server.McpSyncServerExchange;

/** High-performance dispatcher interface generated by the Jooby APT for MCP endpoints. */
public interface McpService {

  default Object invokeTool(String name, Map<String, Object> args, McpSyncServerExchange exchange)
      throws Exception {
    throw new UnsupportedOperationException("tool: " + name + " not supported");
  }

  default Object invokePrompt(String name, Map<String, Object> args, McpSyncServerExchange exchange)
      throws Exception {
    throw new UnsupportedOperationException("prompt: " + name + " not supported");
  }

  default Object readResource(String name, Map<String, Object> args, McpSyncServerExchange exchange)
      throws Exception {
    throw new UnsupportedOperationException("resource: " + name + " not supported");
  }

  default Object readResourceByTemplate(
      String templateUri, Map<String, Object> args, McpSyncServerExchange exchange)
      throws Exception {
    throw new UnsupportedOperationException("resource: " + templateUri + " not supported");
  }

  default Object invokeCompletion(
      String identifier, String argumentName, String input, McpSyncServerExchange exchange)
      throws Exception {
    throw new UnsupportedOperationException("completion: " + identifier + " not supported");
  }
}
