// This file is generated by McpToolProcessor. Do not modify manually.
package io.github.kliushnichenko.jooby.mcp.example;

import io.github.kliushnichenko.jooby.mcp.JoobyMcpServer;
import io.github.kliushnichenko.jooby.mcp.ResourceUri;
import io.github.kliushnichenko.jooby.mcp.internal.MethodInvoker;
import io.github.kliushnichenko.jooby.mcp.internal.ToolSpec;
import io.jooby.Jooby;
import io.modelcontextprotocol.json.McpJsonMapper;
import io.modelcontextprotocol.server.McpSyncServerExchange;
import io.modelcontextprotocol.spec.McpSchema;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.function.Function;
import java.util.function.Supplier;

/**
 * Generated Jooby MCP Server. Do not modify manually.
 */
public class ExampleMcpServer implements JoobyMcpServer {
  private Jooby app;

  private McpJsonMapper mcpJsonMapper;

  /**
   * Map of tool names to its specification.
   */
  private final Map<String, ToolSpec> tools = new HashMap<>();

  /**
   * Map of tool names to method invokers.
   */
  private final Map<String, MethodInvoker> toolInvokers = new HashMap<>();

  /**
   * Map of prompt names to its specification.
   */
  private final Map<String, McpSchema.Prompt> prompts = new HashMap<>();

  /**
   * Map of prompt names to method invokers.
   */
  private final Map<String, MethodInvoker> promptInvokers = new HashMap<>();

  /**
   * List of completions reference objects.
   */
  private final List<McpSchema.CompleteReference> completions = new ArrayList<>();

  /**
   * Map of completion key(a composition of <identifier>_<argumentName>) to method invoker.
   */
  private final Map<String, Function<String, Object>> completionInvokers = new HashMap<>();

  /**
   * List of resources.
   */
  private final List<McpSchema.Resource> resources = new ArrayList<>();

  /**
   * Map of resource URI to method invoker.
   */
  private final Map<String, Supplier<Object>> resourceReaders = new HashMap<>();

  /**
   * List of resource templates.
   */
  private final List<McpSchema.ResourceTemplate> resourceTemplates = new ArrayList<>();

  /**
   * Map of resource URI template to method invoker.
   */
  private final Map<String, Function<Map<String, Object>, Object>> resourceTemplateReaders = new HashMap<>();

  /**
   * Initialize a new server.
   * @param app the Jooby application instance
   * @param mcpJsonMapper json serializer instance
   */
  public void init(final Jooby app, final McpJsonMapper mcpJsonMapper) {
    this.app = app;
    this.mcpJsonMapper = mcpJsonMapper;

    tools.put("elicitation_example", ToolSpec.builder().name("elicitation_example").description("Request the username over elicitation").inputSchema("{\"type\":\"object\",\"properties\":{},\"additionalProperties\":false}").requiredArguments(List.of()).build());
    tools.put("add", ToolSpec.builder().name("add").description("Adds two numbers together").inputSchema("{\"type\":\"object\",\"properties\":{\"first\":{\"type\":\"integer\",\"description\":\"First number to add\"},\"second\":{\"type\":\"integer\",\"description\":\"Second number to add\"}},\"required\":[\"first\",\"second\"],\"additionalProperties\":false}").outputSchema("{\"type\":\"object\",\"properties\":{\"operation\":{\"type\":\"string\"},\"result\":{\"type\":\"number\"},\"expression\":{\"type\":\"string\"}},\"required\":[\"operation\",\"result\",\"expression\"],\"additionalProperties\":false}").requiredArguments(List.of("first", "second")).build());
    tools.put("subtract", ToolSpec.builder().name("subtract").inputSchema("{\"type\":\"object\",\"properties\":{\"a\":{\"type\":\"integer\"},\"b\":{\"type\":\"integer\"}},\"required\":[\"a\",\"b\"],\"additionalProperties\":false}").requiredArguments(List.of("a", "b")).build());
    tools.put("pi_sign_image", ToolSpec.builder().name("pi_sign_image").description("Returns an image of the Pi").inputSchema("{\"type\":\"object\",\"properties\":{},\"additionalProperties\":false}").requiredArguments(List.of()).build());
    tools.put("get_client_info", ToolSpec.builder().name("get_client_info").description("Returns the information about the client initiated the request").inputSchema("{\"type\":\"object\",\"properties\":{},\"additionalProperties\":false}").requiredArguments(List.of()).build());

    toolInvokers.put("elicitation_example", (args, exchange) -> app.require(ElicitationExample.class).requestUsername(exchange));
    toolInvokers.put("add", (args, exchange) -> app.require(ToolsExample.class).add((int) args.get("first"), (int) args.get("second")));
    toolInvokers.put("subtract", (args, exchange) -> app.require(ToolsExample.class).subtract((int) args.get("a"), (int) args.get("b"), exchange));
    toolInvokers.put("pi_sign_image", (args, exchange) -> app.require(ToolsExample.class).getPiSignImage());
    toolInvokers.put("get_client_info", (args, exchange) -> app.require(ToolsExample.class).getClientInfo(exchange));

    prompts.put("summarizeText", new McpSchema.Prompt("summarizeText", "", "Summarizes the provided text into a specified number of sentences", List.of(new McpSchema.PromptArgument("text_to_summarize", null, true), new McpSchema.PromptArgument("maxSentences", null, true))));
    prompts.put("code_review", new McpSchema.Prompt("code_review", "", "Code Review Prompt", List.of(new McpSchema.PromptArgument("codeSnippet", null, true), new McpSchema.PromptArgument("language", null, true), new McpSchema.PromptArgument("scrutinyLevel", null, true))));

    promptInvokers.put("summarizeText", (args, exchange) -> app.require(PromptsExample.class).summarizeText((String) args.get("text_to_summarize"), (String) args.get("maxSentences")));
    promptInvokers.put("code_review", (args, exchange) -> app.require(PromptsExample.class).codeReviewPrompt((String) args.get("codeSnippet"), (String) args.get("language"), (String) args.get("scrutinyLevel")));
    completions.add(new McpSchema.PromptReference("code_review"));
    completions.add(new McpSchema.PromptReference("code_review"));
    completions.add(new McpSchema.ResourceReference("file:///project/{name}"));

    completionInvokers.put("code_review_language", (input) -> app.require(PromptsExample.class).completeCodeReviewLang(input));
    completionInvokers.put("code_review_scrutinyLevel", (input) -> app.require(PromptsExample.class).completeScrutinyLevel(input));
    completionInvokers.put("file:///project/{name}_name", (input) -> app.require(ResourceTemplateExamples.class).projectNameCompletion(input));

    resources.add(McpSchema.Resource.builder().name("README.md").title("README.md").uri("file:///project/README.md").mimeType("text/markdown").build());
    resources.add(McpSchema.Resource.builder().name("blobResource").uri("file:///blob").build());
    resources.add(McpSchema.Resource.builder().name("threadStone").uri("file:///project/thread-stone").size(Long.valueOf(10563)).annotations(new McpSchema.Annotations(List.of(McpSchema.Role.USER, McpSchema.Role.ASSISTANT), 0.3, null)).build());
    resources.add(McpSchema.Resource.builder().name("blackBriar").uri("file:///project/blackbriar/metadata.json").build());

    resourceReaders.put("file:///project/README.md", () -> app.require(ResourceExamples.class).textResource());
    resourceReaders.put("file:///blob", () -> app.require(ResourceExamples.class).blobResource());
    resourceReaders.put("file:///project/thread-stone", () -> app.require(ResourceExamples.class).threadStone());
    resourceReaders.put("file:///project/blackbriar/metadata.json", () -> app.require(ResourceExamples.class).blackBriar());

    resourceTemplates.add(McpSchema.ResourceTemplate.builder().name("get_project").uriTemplate("file:///project/{name}").build());

    resourceTemplateReaders.put("file:///project/{name}", (args) -> app.require(ResourceTemplateExamples.class).getProject((String) args.get("name"), new ResourceUri((String) args.get("__resourceUri"))));

  }

  /**
   * Invokes a tool by name with the provided arguments.
   * @param toolName the name of the tool to invoke
   * @param args the arguments to pass to the tool
   * @return the result of the tool invocation
   */
  public Object invokeTool(final String toolName, final Map<String, Object> args,
      final McpSyncServerExchange exchange) {
    MethodInvoker invoker = toolInvokers.get(toolName);
    return invoker.invoke(args, exchange);
  }

  /**
   *  Invokes a prompt by name with the provided arguments.
   *  @param promptName the name of the prompt to invoke
   *  @param args the arguments to pass to the prompt
   *  @return the result of the prompt invocation
   */
  public Object invokePrompt(final String promptName, final Map<String, Object> args,
      final McpSyncServerExchange exchange) {
    MethodInvoker invoker = promptInvokers.get(promptName);
    return invoker.invoke(args, exchange);
  }

  /**
   * Invokes a completion by identifier(prompt or resource name) and argumentName with the provided
   * argument value.
   * @param identifier prompt or resource template name
   * @param argumentName the name of an argument in prompt or resource template
   * @param input incoming argument value
   * @return the result of the completion invocation
   */
  public Object invokeCompletion(final String identifier, final String argumentName,
      final String input) {
    var completionKey = identifier + '_' + argumentName;
    var invoker = completionInvokers.get(completionKey);
    if (invoker == null) {
        return List.of();
    }
    return invoker.apply(input);
  }

  /**
   * Reads a resource by URI
   * @param uri Resource URI
   * @return resource content
   */
  public Object readResource(final String uri) {
    var reader = resourceReaders.get(uri);
    return reader.get();
  }

  /**
   * Reads a resource by URI according to template
   * @param uriTemplate Resource URI template
   * @return resource content
   */
  public Object readResourceByTemplate(final String uriTemplate, final Map<String, Object> args) {
    var reader = resourceTemplateReaders.get(uriTemplate);
    return reader.apply(args);
  }

  public Map<String, ToolSpec> getTools() {
    return tools;
  }

  public Map<String, McpSchema.Prompt> getPrompts() {
    return prompts;
  }

  public List<McpSchema.CompleteReference> getCompletions() {
    return completions;
  }

  public List<McpSchema.Resource> getResources() {
    return resources;
  }

  public List<McpSchema.ResourceTemplate> getResourceTemplates() {
    return resourceTemplates;
  }

  public String getServerKey() {
    return "example";
  }
}
