/*
 * Jooby https://jooby.io
 * Apache License Version 2.0 https://jooby.io/LICENSE.txt
 * Copyright 2014 Edgar Espina
 */
package issues.i3729.museum;

import static org.junit.jupiter.api.Assertions.assertEquals;

import io.jooby.openapi.OpenAPIResult;
import io.jooby.openapi.OpenAPITest;

public class MuseumTest {

  @OpenAPITest(value = MuseumApp.class)
  public void shouldGenerateDoc(OpenAPIResult result) {
    assertEquals(
        "openapi: 3.1.0\n"
            + "info:\n"
            + "  title: Redocly Museum API\n"
            + "  description: An imaginary, but delightful Museum API for interacting with museum"
            + " services and information. Built with love by Redocly.\n"
            + "  version: 1.0.0\n"
            + "  contact:\n"
            + "    email: team@redocly.com\n"
            + "    url: 'https://redocly.com/docs/cli/'\n"
            + "  x-logo:\n"
            + "    url: 'https://redocly.github.io/redoc/museum-logo.png'\n"
            + "    altText: Museum logo\n"
            + "  license:\n"
            + "    name: MIT\n"
            + "    url: 'https://opensource.org/license/mit/'\n"
            + "servers:\n"
            + "  - url: 'https://api.fake-museum-example.com/v1'\n"
            + "paths:\n"
            + "  /museum-hours:\n"
            + "    get:\n"
            + "      summary: Get museum hours\n"
            + "      description: Get upcoming museum operating hours\n"
            + "      operationId: getMuseumHours\n"
            + "      x-badges:\n"
            + "        - name: 'Beta'\n"
            + "          position: before\n"
            + "          color: purple\n"
            + "      tags:\n"
            + "        - Operations\n"
            + "      parameters:\n"
            + "        - $ref: '#/components/parameters/StartDate'\n"
            + "        - $ref: '#/components/parameters/PaginationPage'\n"
            + "        - $ref: '#/components/parameters/PaginationLimit'\n"
            + "      responses:\n"
            + "        '200':\n"
            + "          description: Success\n"
            + "          content:\n"
            + "            application/json:\n"
            + "              schema:\n"
            + "                $ref: '#/components/schemas/GetMuseumHoursResponse'\n"
            + "              examples:\n"
            + "                default:\n"
            + "                  summary: Museum opening hours\n"
            + "                  value:\n"
            + "                    - date: '2023-09-11'\n"
            + "                      timeOpen: '09:00'\n"
            + "                      timeClose: '18:00'\n"
            + "                    - date: '2023-09-12'\n"
            + "                      timeOpen: '09:00'\n"
            + "                      timeClose: '18:00'\n"
            + "                    - date: '2023-09-13'\n"
            + "                      timeOpen: '09:00'\n"
            + "                      timeClose: '18:00'\n"
            + "                    - date: '2023-09-17'\n"
            + "                      timeOpen: '09:00'\n"
            + "                      timeClose: '18:00'\n"
            + "                closed:\n"
            + "                  summary: The museum is closed\n"
            + "                  value: []\n"
            + "\n"
            + "        '400':\n"
            + "          description: Bad request\n"
            + "        '404':\n"
            + "          description: Not found\n"
            + "  /special-events:\n"
            + "    post:\n"
            + "      security: []\n"
            + "      operationId: CreateSpecialEvent\n"
            + "      summary: Create special event\n"
            + "      tags:\n"
            + "        - Events\n"
            + "      requestBody:\n"
            + "        required: true\n"
            + "        content:\n"
            + "          application/json:\n"
            + "            schema:\n"
            + "              $ref: '#/components/schemas/CreateSpecialEventRequest'\n"
            + "            examples:\n"
            + "              default_example:\n"
            + "                $ref: '#/components/examples/CreateSpecialEventRequestExample'\n"
            + "      responses:\n"
            + "        '200':\n"
            + "          description: success\n"
            + "          content:\n"
            + "            application/json:\n"
            + "              schema:\n"
            + "                $ref: '#/components/schemas/SpecialEventResponse'\n"
            + "              examples:\n"
            + "                default_example:\n"
            + "                  $ref: '#/components/examples/CreateSpecialEventResponseExample'\n"
            + "        '400':\n"
            + "          description: Bad request\n"
            + "        '404':\n"
            + "          description: Not found\n"
            + "    get:\n"
            + "      summary: List special events\n"
            + "      description: Return a list of upcoming special events at the museum.\n"
            + "      security: []\n"
            + "      operationId: listSpecialEvents\n"
            + "      tags:\n"
            + "        - Events\n"
            + "      parameters:\n"
            + "        - name: startDate\n"
            + "          in: query\n"
            + "          description: The starting date to retrieve future operating hours from."
            + " Defaults to today's date.\n"
            + "          schema:\n"
            + "            type: string\n"
            + "            format: date\n"
            + "            example: 2023-02-23\n"
            + "        - name: endDate\n"
            + "          in: query\n"
            + "          description: The end of a date range to retrieve special events for."
            + " Defaults to 7 days after `startDate`.\n"
            + "          schema:\n"
            + "            type: string\n"
            + "            format: date\n"
            + "            example: 2023-04-18\n"
            + "        - name: page\n"
            + "          in: query\n"
            + "          description: The page number to retrieve.\n"
            + "          schema:\n"
            + "            type: integer\n"
            + "            default: 1\n"
            + "            example: 2\n"
            + "        - name: limit\n"
            + "          in: query\n"
            + "          description: The number of days per page.\n"
            + "          schema:\n"
            + "            type: integer\n"
            + "            default: 10\n"
            + "            maximum: 30\n"
            + "            example: 15\n"
            + "\n"
            + "      responses:\n"
            + "        '200':\n"
            + "          description: Success\n"
            + "          content:\n"
            + "            application/json:\n"
            + "              schema:\n"
            + "                $ref: '#/components/schemas/ListSpecialEventsResponse'\n"
            + "              examples:\n"
            + "                default_example:\n"
            + "                  $ref: '#/components/examples/ListSpecialEventsResponseExample'\n"
            + "        '400':\n"
            + "          description: Bad request\n"
            + "        '404':\n"
            + "          description: Not found\n"
            + "  /special-events/{eventId}:\n"
            + "    get:\n"
            + "      summary: Get special event\n"
            + "      description: Get details about a special event.\n"
            + "      operationId: getSpecialEvent\n"
            + "      tags:\n"
            + "        - Events\n"
            + "      parameters:\n"
            + "        - $ref: '#/components/parameters/EventId'\n"
            + "      responses:\n"
            + "        '200':\n"
            + "          description: Success\n"
            + "          content:\n"
            + "            application/json:\n"
            + "              schema:\n"
            + "                $ref: '#/components/schemas/SpecialEventResponse'\n"
            + "              examples:\n"
            + "                default_example:\n"
            + "                  $ref: '#/components/examples/GetSpecialEventResponseExample'\n"
            + "        '400':\n"
            + "          description: Bad request\n"
            + "        '404':\n"
            + "          description: Not found\n"
            + "    patch:\n"
            + "      summary: Update special event\n"
            + "      description: Update the details of a special event\n"
            + "      operationId: updateSpecialEvent\n"
            + "      tags:\n"
            + "        - Events\n"
            + "      parameters:\n"
            + "        - $ref: '#/components/parameters/EventId'\n"
            + "      requestBody:\n"
            + "        required: true\n"
            + "        content:\n"
            + "          application/json:\n"
            + "            schema:\n"
            + "              $ref: '#/components/schemas/UpdateSpecialEventRequest'\n"
            + "            examples:\n"
            + "              default_example:\n"
            + "                $ref: '#/components/examples/UpdateSpecialEventRequestExample'\n"
            + "      responses:\n"
            + "        '200':\n"
            + "          description: Success\n"
            + "          content:\n"
            + "            application/json:\n"
            + "              schema:\n"
            + "                $ref: '#/components/schemas/SpecialEventResponse'\n"
            + "              examples:\n"
            + "                default_example:\n"
            + "                  $ref: '#/components/examples/UpdateSpecialEventResponseExample'\n"
            + "        '400':\n"
            + "          description: Bad request\n"
            + "        '404':\n"
            + "          description: Not found\n"
            + "    delete:\n"
            + "      summary: Delete special event\n"
            + "      description: Delete a special event from the collection. Allows museum to"
            + " cancel planned events.\n"
            + "      operationId: deleteSpecialEvent\n"
            + "      tags:\n"
            + "        - Events\n"
            + "      parameters:\n"
            + "        - $ref: '#/components/parameters/EventId'\n"
            + "      responses:\n"
            + "        '204':\n"
            + "          description: Success - no content\n"
            + "        '400':\n"
            + "          description: Bad request\n"
            + "        '401':\n"
            + "          description: Unauthorized\n"
            + "        '404':\n"
            + "          description: Not found\n"
            + "  /tickets:\n"
            + "    post:\n"
            + "      summary: Buy museum tickets\n"
            + "      description: Purchase museum tickets for general entry or special events.\n"
            + "      operationId: buyMuseumTickets\n"
            + "      tags:\n"
            + "        - Tickets\n"
            + "      requestBody:\n"
            + "        required: true\n"
            + "        content:\n"
            + "          application/json:\n"
            + "            schema:\n"
            + "              $ref: '#/components/schemas/BuyMuseumTicketsRequest'\n"
            + "            examples:\n"
            + "              general_entry:\n"
            + "                $ref: '#/components/examples/BuyGeneralTicketsRequestExample'\n"
            + "              event_entry:\n"
            + "                $ref: '#/components/examples/BuyEventTicketsRequestExample'\n"
            + "      responses:\n"
            + "        '200':\n"
            + "          description: Success\n"
            + "          content:\n"
            + "            application/json:\n"
            + "              schema:\n"
            + "                $ref: '#/components/schemas/BuyMuseumTicketsResponse'\n"
            + "              examples:\n"
            + "                general_entry:\n"
            + "                  $ref: '#/components/examples/BuyGeneralTicketsResponseExample'\n"
            + "                event_entry:\n"
            + "                  $ref: '#/components/examples/BuyEventTicketsResponseExample'\n"
            + "        '400':\n"
            + "          description: Bad request\n"
            + "        '404':\n"
            + "          description: Not found\n"
            + "  /tickets/{ticketId}/qr:\n"
            + "    get:\n"
            + "      summary: Get ticket QR code\n"
            + "      description: Return an image of your ticket with scannable QR code. Used for"
            + " event entry.\n"
            + "      operationId: getTicketCode\n"
            + "      tags:\n"
            + "        - Tickets\n"
            + "      parameters:\n"
            + "        - $ref: '#/components/parameters/TicketId'\n"
            + "      responses:\n"
            + "        '200':\n"
            + "          description: Scannable event ticket in image format\n"
            + "          content:\n"
            + "            image/png:\n"
            + "              schema:\n"
            + "                $ref: '#/components/schemas/GetTicketCodeResponse'\n"
            + "        '400':\n"
            + "          description: Bad request\n"
            + "        '404':\n"
            + "          description: Not found\n"
            + "components:\n"
            + "  schemas:\n"
            + "    SpecialEvent:\n"
            + "      description: Request payload for creating new special events at the museum.\n"
            + "      properties:\n"
            + "        name:\n"
            + "          description: Name of the special event\n"
            + "          type: string\n"
            + "          example: Fossil lecture\n"
            + "        location:\n"
            + "          description: Location where the special event is held\n"
            + "          type: string\n"
            + "          example: Lecture theatre\n"
            + "        eventDescription:\n"
            + "          description: Description of the special event\n"
            + "          type: string\n"
            + "          example: Our panel of experts will share their favorite fossils and"
            + " explain why they are so great.\n"
            + "        dates:\n"
            + "          description: List of planned dates for the special event\n"
            + "          type: array\n"
            + "          items:\n"
            + "            type: string\n"
            + "            format: date\n"
            + "            example: 2024-03-29\n"
            + "        price:\n"
            + "          description: Price of a ticket for the special event\n"
            + "          type: number\n"
            + "          format: float\n"
            + "          example: 12.50\n"
            + "\n"
            + "    TicketType:\n"
            + "      description: Type of ticket being purchased. Use `general` for regular museum"
            + " entry and `event` for tickets to special events.\n"
            + "      type: string\n"
            + "      enum:\n"
            + "        - event\n"
            + "        - general\n"
            + "      example: event\n"
            + "    Date:\n"
            + "      type: string\n"
            + "      format: date\n"
            + "      example: 2023-10-29\n"
            + "    Email:\n"
            + "      description: Email address for ticket purchaser.\n"
            + "      type: string\n"
            + "      format: email\n"
            + "      example: museum-lover@example.com\n"
            + "    Phone:\n"
            + "      description: Phone number for the ticket purchaser (optional).\n"
            + "      type: string\n"
            + "      example: +1(234)-567-8910\n"
            + "    BuyMuseumTicketsRequest:\n"
            + "      description: Request payload used for purchasing museum tickets.\n"
            + "      type: object\n"
            + "      properties:\n"
            + "        ticketType:\n"
            + "          $ref: '#/components/schemas/TicketType'\n"
            + "        eventId:\n"
            + "          description: Unique identifier for a special event. Required if purchasing"
            + " tickets for the museum's special events.\n"
            + "          $ref: '#/components/schemas/EventId'\n"
            + "        ticketDate:\n"
            + "          description: Date that the ticket is valid for.\n"
            + "          $ref: '#/components/schemas/Date'\n"
            + "        email:\n"
            + "          $ref: '#/components/schemas/Email'\n"
            + "        phone:\n"
            + "          $ref: '#/components/schemas/Phone'\n"
            + "      required:\n"
            + "        - ticketType\n"
            + "        - ticketDate\n"
            + "        - email\n"
            + "    TicketMessage:\n"
            + "      description: Confirmation message after a ticket purchase.\n"
            + "      type: string\n"
            + "      example: Museum general entry ticket purchased\n"
            + "    TicketId:\n"
            + "      description: Unique identifier for museum ticket. Generated when purchased.\n"
            + "      type: string\n"
            + "      format: uuid\n"
            + "      example: a54a57ca-36f8-421b-a6b4-2e8f26858a4c\n"
            + "    TicketConfirmation:\n"
            + "      description: Unique confirmation code used to verify ticket purchase.\n"
            + "      type: string\n"
            + "      example: ticket-event-a98c8f-7eb12\n"
            + "    BuyMuseumTicketsResponse:\n"
            + "      description: Details for a museum ticket after a successful purchase.\n"
            + "      type: object\n"
            + "      properties:\n"
            + "        message:\n"
            + "          $ref: '#/components/schemas/TicketMessage'\n"
            + "        eventName:\n"
            + "          $ref: '#/components/schemas/EventName'\n"
            + "        ticketId:\n"
            + "          $ref: '#/components/schemas/TicketId'\n"
            + "        ticketType:\n"
            + "          $ref: '#/components/schemas/TicketType'\n"
            + "        ticketDate:\n"
            + "          description: Date the ticket is valid for.\n"
            + "          $ref: '#/components/schemas/Date'\n"
            + "        confirmationCode:\n"
            + "          $ref: '#/components/schemas/TicketConfirmation'\n"
            + "      required:\n"
            + "        - message\n"
            + "        - ticketId\n"
            + "        - ticketType\n"
            + "        - ticketDate\n"
            + "        - confirmationCode\n"
            + "    GetTicketCodeResponse:\n"
            + "      description: An image of a ticket with a QR code used for museum or event"
            + " entry.\n"
            + "      type: string\n"
            + "      format: binary\n"
            + "    GetMuseumHoursResponse:\n"
            + "      description: List of museum operating hours for consecutive days.\n"
            + "      type: array\n"
            + "      items:\n"
            + "        $ref: '#/components/schemas/MuseumDailyHours'\n"
            + "    MuseumDailyHours:\n"
            + "      description: Daily operating hours for the museum.\n"
            + "      type: object\n"
            + "      properties:\n"
            + "        date:\n"
            + "          description: Date the operating hours apply to.\n"
            + "          $ref: '#/components/schemas/Date'\n"
            + "          example: 2024-12-31\n"
            + "        timeOpen:\n"
            + "          type: string\n"
            + "          pattern: '^([01]\\d|2[0-3]):?([0-5]\\d)$'\n"
            + "          description: Time the museum opens on a specific date. Uses 24 hour time"
            + " format (`HH:mm`).\n"
            + "          example: 09:00\n"
            + "        timeClose:\n"
            + "          description: Time the museum closes on a specific date. Uses 24 hour time"
            + " format (`HH:mm`).\n"
            + "          type: string\n"
            + "          pattern: '^([01]\\d|2[0-3]):?([0-5]\\d)$'\n"
            + "          example: 18:00\n"
            + "      required:\n"
            + "        - date\n"
            + "        - timeOpen\n"
            + "        - timeClose\n"
            + "    EventId:\n"
            + "      description: Identifier for a special event.\n"
            + "      type: string\n"
            + "      format: uuid\n"
            + "      example: 3be6453c-03eb-4357-ae5a-984a0e574a54\n"
            + "    EventName:\n"
            + "      type: string\n"
            + "      description: Name of the special event\n"
            + "      example: Pirate Coding Workshop\n"
            + "    EventLocation:\n"
            + "      type: string\n"
            + "      description: Location where the special event is held\n"
            + "      example: Computer Room\n"
            + "    EventDescription:\n"
            + "      type: string\n"
            + "      description: Description of the special event\n"
            + "      example: Captain Blackbeard shares his love of the C...language. And possibly"
            + " Arrrrr (R lang).\n"
            + "    EventDates:\n"
            + "      type: array\n"
            + "      items:\n"
            + "        $ref: '#/components/schemas/Date'\n"
            + "      description: List of planned dates for the special event\n"
            + "    EventPrice:\n"
            + "      description: Price of a ticket for the special event\n"
            + "      type: number\n"
            + "      format: float\n"
            + "      example: 25\n"
            + "    CreateSpecialEventRequest:\n"
            + "      description: Request payload for creating new special events at the museum.\n"
            + "      properties:\n"
            + "        name:\n"
            + "          $ref: '#/components/schemas/EventName'\n"
            + "        location:\n"
            + "          $ref: '#/components/schemas/EventLocation'\n"
            + "        eventDescription:\n"
            + "          $ref: '#/components/schemas/EventDescription'\n"
            + "        dates:\n"
            + "          $ref: '#/components/schemas/EventDates'\n"
            + "        price:\n"
            + "          $ref: '#/components/schemas/EventPrice'\n"
            + "      required:\n"
            + "        - name\n"
            + "        - location\n"
            + "        - eventDescription\n"
            + "        - dates\n"
            + "        - price\n"
            + "    UpdateSpecialEventRequest:\n"
            + "      description: Request payload for updating an existing special event. Only"
            + " included fields are updated in the event.\n"
            + "      properties:\n"
            + "        name:\n"
            + "          $ref: '#/components/schemas/EventName'\n"
            + "        location:\n"
            + "          $ref: '#/components/schemas/EventLocation'\n"
            + "        eventDescription:\n"
            + "          $ref: '#/components/schemas/EventDescription'\n"
            + "        dates:\n"
            + "          $ref: '#/components/schemas/EventDates'\n"
            + "        price:\n"
            + "          $ref: '#/components/schemas/EventPrice'\n"
            + "    ListSpecialEventsResponse:\n"
            + "      description: A list of upcoming special events\n"
            + "      type: array\n"
            + "      items:\n"
            + "        $ref: '#/components/schemas/SpecialEventResponse'\n"
            + "    SpecialEventResponse:\n"
            + "      description: Information about a special event.\n"
            + "      properties:\n"
            + "        eventId:\n"
            + "          $ref: '#/components/schemas/EventId'\n"
            + "        name:\n"
            + "          $ref: '#/components/schemas/EventName'\n"
            + "        location:\n"
            + "          $ref: '#/components/schemas/EventLocation'\n"
            + "        eventDescription:\n"
            + "          $ref: '#/components/schemas/EventDescription'\n"
            + "        dates:\n"
            + "          $ref: '#/components/schemas/EventDates'\n"
            + "        price:\n"
            + "          $ref: '#/components/schemas/EventPrice'\n"
            + "      required:\n"
            + "        - eventId\n"
            + "        - name\n"
            + "        - location\n"
            + "        - eventDescription\n"
            + "        - dates\n"
            + "        - price\n"
            + "  securitySchemes:\n"
            + "    MuseumPlaceholderAuth:\n"
            + "      type: http\n"
            + "      scheme: basic\n"
            + "  examples:\n"
            + "    BuyGeneralTicketsRequestExample:\n"
            + "      summary: General entry ticket\n"
            + "      value:\n"
            + "        ticketType: general\n"
            + "        ticketDate: 2023-09-07\n"
            + "        email: todd@example.com\n"
            + "    BuyEventTicketsRequestExample:\n"
            + "      summary: Special event ticket\n"
            + "      value:\n"
            + "        ticketType: general\n"
            + "        eventId: dad4bce8-f5cb-4078-a211-995864315e39\n"
            + "        ticketDate: 2023-09-05\n"
            + "        email: todd@example.com\n"
            + "    BuyGeneralTicketsResponseExample:\n"
            + "      summary: General entry ticket\n"
            + "      value:\n"
            + "        message: Museum general entry ticket purchased\n"
            + "        ticketId: 382c0820-0530-4f4b-99af-13811ad0f17a\n"
            + "        ticketType: general\n"
            + "        ticketDate: 2023-09-07\n"
            + "        confirmationCode: ticket-general-e5e5c6-dce78\n"
            + "    BuyEventTicketsResponseExample:\n"
            + "      summary: Special event ticket\n"
            + "      value:\n"
            + "        message: Museum special event ticket purchased\n"
            + "        ticketId: b811f723-17b2-44f7-8952-24b03e43d8a9\n"
            + "        eventName: Mermaid Treasure Identification and Analysis\n"
            + "        ticketType: event\n"
            + "        ticketDate: 2023-09-05\n"
            + "        confirmationCode: ticket-event-9c55eg-8v82a\n"
            + "    CreateSpecialEventRequestExample:\n"
            + "      summary: Create special event\n"
            + "      value:\n"
            + "        name: Mermaid Treasure Identification and Analysis\n"
            + "        location: Under the seaaa \uD83E\uDD80 \uD83C\uDFB6 \uD83C\uDF0A.\n"
            + "        eventDescription: Join us as we review and classify a rare collection of 20"
            + " thingamabobs, gadgets, gizmos, whoosits, and whatsits, kindly donated by Ariel.\n"
            + "        dates:\n"
            + "          - 2023-09-05\n"
            + "          - 2023-09-08\n"
            + "        price: 0\n"
            + "    CreateSpecialEventResponseExample:\n"
            + "      summary: Special event created\n"
            + "      value:\n"
            + "        eventId: dad4bce8-f5cb-4078-a211-995864315e39\n"
            + "        name: Mermaid Treasure Identification and Analysis\n"
            + "        location: Under the seaaa \uD83E\uDD80 \uD83C\uDFB6 \uD83C\uDF0A.\n"
            + "        eventDescription: Join us as we review and classify a rare collection of 20"
            + " thingamabobs, gadgets, gizmos, whoosits, and whatsits, kindly donated by Ariel.\n"
            + "        dates:\n"
            + "          - 2023-09-05\n"
            + "          - 2023-09-08\n"
            + "        price: 30\n"
            + "    GetSpecialEventResponseExample:\n"
            + "      summary: Get special event\n"
            + "      value:\n"
            + "        eventId: 6744a0da-4121-49cd-8479-f8cc20526495\n"
            + "        name: Time Traveler Tea Party\n"
            + "        location: Temporal Tearoom\n"
            + "        eventDescription: Sip tea with important historical figures.\n"
            + "        dates:\n"
            + "          - 2023-11-18\n"
            + "          - 2023-11-25\n"
            + "          - 2023-12-02\n"
            + "        price: 60\n"
            + "    ListSpecialEventsResponseExample:\n"
            + "      summary: List of special events\n"
            + "      value:\n"
            + "        - eventId: f3e0e76e-e4a8-466e-ab9c-ae36c15b8e97\n"
            + "          name: Sasquatch Ballet\n"
            + "          location: Seattle... probably\n"
            + "          eventDescription: They're big, they're hairy, but they're also graceful."
            + " Come learn how the biggest feet can have the lightest touch.\n"
            + "          dates:\n"
            + "            - 2023-12-15\n"
            + "            - 2023-12-22\n"
            + "          price: 40\n"
            + "        - eventId: 2f14374a-9c65-4ee5-94b7-fba66d893483\n"
            + "          name: Solar Telescope Demonstration\n"
            + "          location: Far from the sun.\n"
            + "          eventDescription: Look at the sun without going blind!\n"
            + "          dates:\n"
            + "            - 2023-09-07\n"
            + "            - 2023-09-14\n"
            + "          price: 50\n"
            + "        - eventId: 6aaa61ba-b2aa-4868-b803-603dbbf7bfdb\n"
            + "          name: Cook like a Caveman\n"
            + "          location: Fire Pit on East side\n"
            + "          eventDescription: Learn to cook on an open flame.\n"
            + "          dates:\n"
            + "            - 2023-11-10\n"
            + "            - 2023-11-17\n"
            + "            - 2023-11-24\n"
            + "          price: 5\n"
            + "        - eventId: 602b75e1-5696-4ab8-8c7a-f9e13580f910\n"
            + "          name: Underwater Basket Weaving\n"
            + "          location: Rec Center Pool next door.\n"
            + "          eventDescription: Learn to weave baskets underwater.\n"
            + "          dates:\n"
            + "            - 2023-09-12\n"
            + "            - 2023-09-15\n"
            + "          price: 15\n"
            + "        - eventId: dad4bce8-f5cb-4078-a211-995864315e39\n"
            + "          name: Mermaid Treasure Identification and Analysis\n"
            + "          location: Room Sea-12\n"
            + "          eventDescription: Join us as we review and classify a rare collection of"
            + " 20 thingamabobs, gadgets, gizmos, whoosits, and whatsits — kindly donated by"
            + " Ariel.\n"
            + "          dates:\n"
            + "            - 2023-09-05\n"
            + "            - 2023-09-08\n"
            + "          price: 30\n"
            + "        - eventId: 6744a0da-4121-49cd-8479-f8cc20526495\n"
            + "          name: Time Traveler Tea Party\n"
            + "          location: Temporal Tearoom\n"
            + "          eventDescription: Sip tea with important historical figures.\n"
            + "          dates:\n"
            + "            - 2023-11-18\n"
            + "            - 2023-11-25\n"
            + "            - 2023-12-02\n"
            + "          price: 60\n"
            + "        - eventId: 3be6453c-03eb-4357-ae5a-984a0e574a54\n"
            + "          name: Pirate Coding Workshop\n"
            + "          location: Computer Room\n"
            + "          eventDescription: Captain Blackbeard shares his love of the C...language."
            + " And possibly Arrrrr (R lang).\n"
            + "          dates:\n"
            + "            - 2023-10-29\n"
            + "            - 2023-10-30\n"
            + "            - 2023-10-31\n"
            + "          price: 45\n"
            + "        - eventId: 9d90d29a-2af5-4206-97d9-9ea9ceadcb78\n"
            + "          name: Llama Street Art Through the Ages\n"
            + "          location: Auditorium\n"
            + "          eventDescription: Llama street art?! Alpaca my bags -- let's go!\n"
            + "          dates:\n"
            + "            - 2023-10-29\n"
            + "            - 2023-10-30\n"
            + "            - 2023-10-31\n"
            + "          price: 45\n"
            + "        - eventId: a3c7b2c4-b5fb-4ef7-9322-00a919864957\n"
            + "          name: The Great Parrot Debate\n"
            + "          location: Outdoor Amphitheatre\n"
            + "          eventDescription: See leading parrot minds discuss important geopolitical"
            + " issues.\n"
            + "          dates:\n"
            + "            - 2023-11-03\n"
            + "            - 2023-11-10\n"
            + "          price: 35\n"
            + "        - eventId: b92d46b7-4c5d-422b-87a5-287767e26f29\n"
            + "          name: Eat a Bunch of Corn\n"
            + "          location: Cafeteria\n"
            + "          eventDescription: We accidentally bought too much corn. Please come eat"
            + " it.\n"
            + "          dates:\n"
            + "            - 2023-11-10\n"
            + "            - 2023-11-17\n"
            + "            - 2023-11-24\n"
            + "          price: 5\n"
            + "    UpdateSpecialEventRequestExample:\n"
            + "      summary: Update special event request\n"
            + "      value:\n"
            + "        location: On the beach.\n"
            + "        price: 15\n"
            + "    UpdateSpecialEventResponseExample:\n"
            + "      summary: Update special event\n"
            + "      value:\n"
            + "        eventId: dad4bce8-f5cb-4078-a211-995864315e39\n"
            + "        name: Mermaid Treasure Identification and Analysis\n"
            + "        location: On the beach.\n"
            + "        eventDescription: Join us as we review and classify a rare collection of 20"
            + " thingamabobs, gadgets, gizmos, whoosits, and whatsits, kindly donated by Ariel.\n"
            + "        dates:\n"
            + "          - 2023-09-05\n"
            + "          - 2023-09-08\n"
            + "        price: 15\n"
            + "    GetMuseumHours:\n"
            + "      summary: Museum opening hours\n"
            + "      value:\n"
            + "        - date: '2023-09-11'\n"
            + "          timeOpen: '09:00'\n"
            + "          timeClose: '18:00'\n"
            + "        - date: '2023-09-12'\n"
            + "          timeOpen: '09:00'\n"
            + "          timeClose: '18:00'\n"
            + "        - date: '2023-09-13'\n"
            + "          timeOpen: '09:00'\n"
            + "          timeClose: '18:00'\n"
            + "        - date: '2023-09-14'\n"
            + "          timeOpen: '09:00'\n"
            + "          timeClose: '18:00'\n"
            + "        - date: '2023-09-15'\n"
            + "          timeOpen: '10:00'\n"
            + "          timeClose: '16:00'\n"
            + "        - date: '2023-09-18'\n"
            + "          timeOpen: '09:00'\n"
            + "          timeClose: '18:00'\n"
            + "        - date: '2023-09-19'\n"
            + "          timeOpen: '09:00'\n"
            + "          timeClose: '18:00'\n"
            + "        - date: '2023-09-20'\n"
            + "          timeOpen: '09:00'\n"
            + "          timeClose: '18:00'\n"
            + "        - date: '2023-09-21'\n"
            + "          timeOpen: '09:00'\n"
            + "          timeClose: '18:00'\n"
            + "        - date: '2023-09-22'\n"
            + "          timeOpen: '10:00'\n"
            + "          timeClose: '16:00'\n"
            + "    ClosedMuseumHours:\n"
            + "      summary: The museum is closed\n"
            + "      value: []\n"
            + "  parameters:\n"
            + "    PaginationPage:\n"
            + "      name: page\n"
            + "      in: query\n"
            + "      description: The page number to retrieve.\n"
            + "      schema:\n"
            + "        type: integer\n"
            + "        default: 1\n"
            + "        example: 2\n"
            + "    PaginationLimit:\n"
            + "      name: limit\n"
            + "      in: query\n"
            + "      description: The number of days per page.\n"
            + "      schema:\n"
            + "        type: integer\n"
            + "        default: 10\n"
            + "        maximum: 30\n"
            + "        example: 15\n"
            + "    EventId:\n"
            + "      name: eventId\n"
            + "      in: path\n"
            + "      description: An identifier for a special event.\n"
            + "      required: true\n"
            + "      schema:\n"
            + "        type: string\n"
            + "        format: uuid\n"
            + "        example: dad4bce8-f5cb-4078-a211-995864315e39\n"
            + "    StartDate:\n"
            + "      name: startDate\n"
            + "      in: query\n"
            + "      description: The starting date to retrieve future operating hours from."
            + " Defaults to today's date.\n"
            + "      schema:\n"
            + "        type: string\n"
            + "        format: date\n"
            + "        example: 2023-02-23\n"
            + "    EndDate:\n"
            + "      name: endDate\n"
            + "      in: query\n"
            + "      description: The end of a date range to retrieve special events for. Defaults"
            + " to 7 days after `startDate`.\n"
            + "      schema:\n"
            + "        type: string\n"
            + "        format: date\n"
            + "        example: 2023-04-18\n"
            + "    TicketId:\n"
            + "      name: ticketId\n"
            + "      in: path\n"
            + "      description: An identifier for a ticket to a museum event. Used to generate"
            + " ticket image.\n"
            + "      required: true\n"
            + "      schema:\n"
            + "        type: string\n"
            + "        format: uuid\n"
            + "        example: a54a57ca-36f8-421b-a6b4-2e8f26858a4c\n"
            + "\n"
            + "tags:\n"
            + "  - name: Operations\n"
            + "    x-displayName: About the museum\n"
            + "    description: Operational information about the museum.\n"
            + "  - name: Events\n"
            + "    x-displayName: Upcoming events\n"
            + "    description: Special events hosted by the Museum.\n"
            + "  - name: Tickets\n"
            + "    x-displayName: Buy tickets\n"
            + "    description: Museum tickets for general entrance or special events.\n"
            + "\n"
            + "x-tagGroups:\n"
            + "  - name: Plan your visit\n"
            + "    tags:\n"
            + "      - Operations\n"
            + "      - Events\n"
            + "  - name: Purchases\n"
            + "    tags:\n"
            + "      - Tickets\n"
            + "\n"
            + "    urity:\n"
            + "  - MuseumPlaceholderAuth: []",
        result.toYaml());
  }
}
