== Context

javadoc:Context[Context] gives you access to `HTTP Request/Response`.

=== Parameters

There are four parameter types: `path`, `query`, `form` and `multipart`. All them share an unified
API for accessing and parsing to their values.

We are going to describe them briefly in the next sections, then go into specific features of the
javadoc:Value[Value API].

[id=http-header]
==== Header

HTTP headers allow the client and the server to pass additional information with the request or the
response. An HTTP header consists of its case-insensitive name followed by a colon `:`, then by its 
value (without line breaks). Leading white space before the value is ignored.

.Header API:
[source, java]
----
{
  get("/" ctx -> {
    String token = ctx.header("token").value();            // <1>

    Value headers = ctx.headers();                         // <2>

    Map<String, List<String>> headerMap = ctx.headerMap(); // <3>
    ...
  });
  
}
----

<1> Header variable `token`
<2> All headers as javadoc:Value[]
<3> All headers as a `multi-value` map

==== Path

Path parameter are part of the `URI`. To define a path variable you need to use the `{..}` notation.

.Syntax:
[source,java]
----
{
  get("/{id}" ctx -> ctx.path("id").value());                                 // <1>
  
  get("/@{id}" ctx -> ctx.path("id").value());                                // <2>
  
  get("/file/{name}.{ext}", ctx -> cxt.path("name") + "." + ctx.path("ext")); // <3>
  
  get("/file/*", ctx -> ctx.path("*"))                                        // <4>

  get("/{id:[0-9]+}", ctx -> ctx.path("id))                                    // <5>
}
----

<1> Path variable `id`
<2> Path variable `id` prefixed with `@`
<3> Multiple variables `name` and `ext`
<4> Unnamed catchall path variable
<5> Path variable with a regular expression

.Path:
[source, java]
----
{
  get("/{name}", ctx -> {
    String pathString = ctx.pathString();         // <1>
    
    Value path = ctx.path();                      // <2>
    
    Map<String, String> pathMap = ctx.pathMap();  // <3>

    String name = ctx.path("name").value();       // <4>

    ...    
  });
}
----

<1> Access to the `raw` path string:

- `/a+b`    => `/a+b`
- `/a b`    => `/a%20b`  (not decoded)
- `/%2F%2B` => `/%2F%2B` (not decoded)

<2> Path as javadoc:Value[] object:

- `/a+b`    => `{name=a+b}`
- `/a b`    => `{name=a b}` (decoded)
- `/%2F%2B` => `{name=/+}`  (decoded)

<3> Path as `Map<String, String>` object:

- `/a+b`    => `{name=a+b}`
- `/a b`    => `{name=a b}` (decoded)
- `/%2F%2B` => `{name=/+}`  (decoded)

<4> Path variable `name` as `String`: 

- `/a+b`    => `a+b`
- `/a b`    => `a b`  (decoded)
- `/%2F%2B` => `/+`   (decoded)

==== Query

[source, java]
----
{
  get("/search", ctx -> {
    String queryString = ctx.queryString();                    // <1>

    QueryString query = ctx.query();                           // <2>

    Map<String, List<String>> queryMap = ctx.queryMultimap();  // <3>

    String q = ctx.query("q").value();                         // <4>

    SearchQuery searchQuery = ctx.query(SearchQuery.class);    // <5>

    ...
  });
}

class SearchQuery {

   public final String q;

   public SearchQuery(String q) {
     this.q = q;
   }
}
----

<1> Access to `raw` queryString:

- `/search`       => `""` (empty)
- `/search?q=a+b` => `?q=a+b`
- `/search?q=a b` => `?q=a%20b` (not decoded)

<2> Query String as javadoc:QueryString[] object:

- `/search`       => `{}`      (empty)
- `/search?q=a+b` => `{q=a+b}` 
- `/search?q=a b` => `{q=a b}` (decoded)

<3> Query string as `multi-value map`

- `/search`       => `{}`       (empty) 
- `/search?q=a+b` => `{q=[a+b]}`
- `/search?q=a b` => `{q=[a b]}`  (decoded)

<4> Access to decoded variable `q`:

- `/search`       => `Bad Request (400). Missing value: "q"`
- `/search?q=a+b` => `a+b`
- `/search?q=a b` => `a b` (decoded)

<5> Query string as `SearchQuery`

- `/search`       => `Bad Request (400). Missing value: "q"`
- `/search?q=a+b` => `SearchQuery(q="a+b")`
- `/search?q=a b` => `SearchQuery(q="a b")` (decoded)

==== Formdata

[source, java]
----
{
  post("/user", ctx -> {
    Formdata form = ctx.form();                                // <1>

    Map<String, List<String> formMap = ctx.formMultimap();  // <2>

    String userId = ctx.form("id").value();                 // <3>
    
    String pass = ctx.form("pass").value();                 // <4>

    User user = ctx.form(User.class);                       // <5>

    
    ...
  });
}

class User {

   public final String id;

   public final String pass;

   public User(String id, String pass) {
     this.id = id;
     this.pass = pass;
   }
}
----

----
curl -d "id=root&pass=pwd" -X POST http://localhost:8080/user
----

<1> Form as javadoc:Formdata[] => `{id=root, pass=pwd}`
<2> Form as `multi-value map`  => `{id=root, pass=[pwd]}`
<3> Form variable `id`         => `root`
<4> Form variable `pass`       => `pwd`
<5> Form as `User` object      => `User(id=root, pass=pwd)`

[NOTE]
====
Form data must be encoded as `application/x-www-form-urlencoded`
====

==== Multipart

[source, java]
----
{
  post("/user", ctx -> {
    Multipart multipart = ctx.multipart();                            // <1>

    Map<String, List<String> multipartMap = ctx.multipartMultimap();  // <2>
   
    String userId = ctx.multipart("id").value();                      // <3>
    
    String pass = ctx.multipart("pass").value();                      // <4>
    
    FileUpload pic = ctx.multipart("pic").fileUpload();               // <5>

    User user = ctx.multipart(User.class);                            // <6>

    ...
  });
}

class User {

   public final String id;

   public final String pass;
   
   public final FileUpload pic;

   public User(String id, String pass, FileUpload pic) {
     this.id = id;
     this.pass = pass;
     this.pic = pic;
   }
}
----

----
curl -F id=root -F pass=root -F pic=@/path/to/local/file/profile.png http://localhost:8080/user
----

<1> Form as javadoc:Multipart[] => `{id=root, pass=pwd, pic=profile.png}`
<2> Form as `multi-value map`  => `{id=root, pass=[pwd]}`
<3> Form variable `id`         => `root`
<4> Form variable `pass`       => `pwd`
<5> javadoc:FileUpload[] variable `pic`
<6> Form as `User` object      => `User(id=root, pass=pwd, pic=profile.png)`

[TIP]
.File Upload
====

You may prefer to use one of the utility methods:

[source,java]
----
  FileUpload pic = ctx.file("pic");         // <1>

  List<FileUpload> pic = ctx.files("pic");  // <2>

  List<FileUpload> files = ctx.files();     // <3>
----

<1> Single file upload named `pic`
<2> Multiple file uploads named `pic`
<3> All file uploads

====

[NOTE]
====
Form data must be encoded as `multipart/form-data`
====

include::value-api.adoc[]

include::body.adoc[]
