////
Style guidelines:

* Refer to the project in prose as simply Jooby, with no adornment or formatting. Enclose the class
  name `Jooby` in back ticks so readers can distinguish references to the `Jooby` class from 
  references to the Jooby project as a whole.
* 100 characters per line, except when you can't break it up e.g. links or asciidoc directives
* Avoid class definition on Jooby code examples. Always start an example with `{...}`
* Avoid JUnit boilerplate in code examples. Assertions are ok if they complement the example.
* External links should use a caret at the end of the link title e.g.
  link:path/to/doc[the title^] so they open in separate tabs. See
  http://asciidoctor.org/docs/asciidoc-writers-guide/#target-window-and-role-attributes-for-links
* Be funny. Nobody like reading dry documentation.
* Be inclusive: keep usage of male and female names equal in code examples.
* Best edited while drunk

////

= Welcome to Jooby!

[discrete]
== &infin; do more, more easily 

== Introduction

Jooby is a modern, performant and easy to use web framework for Java and Kotlin built on top of your favorite web server.

.Welcome!!
[source,java,role="primary"]
----
import io.jooby.Jooby;

public class App extends Jooby {

  {
    get("/", ctx -> {
      return "Welcome to Jooby!";
    }); 
  }

  public static void main(String[] args) {
    run(App::new, args);
  }
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
import io.jooby.run

fun main(args: Array<String>) {
  run(args) {
    get ("/) { ctx ->
      "Welcome to Jooby!"
    }
  }
}
----

=== Status

[IMPORTANT]
====
There is no stable release yet for `2.0.0`. API may change between milestone releases without warning.

This is a **work-in-progress** document and contains documentation and examples of what is ready to use. If it is not documented here, it is not implemented.

Not ready yet? Try https://jooby.org[Jooby 1.x] 

Thank you {love}
====

=== Micro and Fullstack

Jooby is a modular micro framework. At the core level:
  
- Reflection and annotation free
- Only HTTP Routing
- Multi Server: link:server/jetty.html[Jetty], link:server/netty.html[Netty], link:server/undertow.html[Undertow]

Now, if you need more... Jooby don't leave you alone:

- MVC programming model (subset of https://github.com/jax-rs[JAX-RS])
- Module ecosytem

=== Script API

Script API (a.k.a script routes) provides a fluent DSL, reflection and annotation free based on `lambda` functions.

We usually extends `Jooby` and define routes in the instance initializer:

.Script:
[source,java,role="primary"]
----
import io.jooby.Jooby;

public class App extends Jooby {

  {
    get("/", ctx -> {
      return "Hello Jooby!";
    }); 
  }

  public static void main(String[] args) {
    run(App::new, args);
  }
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
import io.jooby.Kooby;
import io.jooby.run;

class App : Kooby({

  get("/") { ctx ->
    "Hello Jooby!"
  }

})

fun main(args: Array<String>) {
  run(::App, args)
}
----

This is not strictly necessary (of course), you may create a `Jooby` application like:

.No-subclass bootstrap:
[source,java,role="primary"]
----
import io.jooby.Jooby;

public class App {

  public static void main(String[] args) {
    run(() -> {
      Jooby app = new Jooby();

      app.get("/", ctx -> {
        return "Hello Jooby!";
      });

      return app;
    }, args);
  }
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
import io.jooby.run

fun main(args: Array<String>) {
  run(args) {
    get("/") { ctx ->
      "Hello Jooby!"
    }
  }
}
----

[#introduction-mvc-api]
=== MVC API

On the other hand, the MVC API (a.k.a mvc routes) uses annotation and reflection to define/execute routes.
Jooby implements a subset of https://github.com/jax-rs[JAX-RS] but not intended to be a fully
https://github.com/jax-rs[JAX-RS] compliant implementation.

.MVC API:
[source,java,role="primary"]
----
public class App extends Jooby {

  {
    use(new MyController());
  }

  public static void main(String[] args) {
    run(App::new, args);
  }
}

public class MyController {

  @GET
  public String sayHi() {
    return "Hello Jooby!";
  }
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
class App : Kooby({

    use(MyController())

})

fun main(args: Array<String>) {
  run(::App, args)
}

class MyController {

  @GET
  fun sayHi() : String {
    return "Hello Jooby!"
  }
}
----

include::getting-started.adoc[]

include::routing.adoc[]

include::context.adoc[]

include::execution-model.adoc[]

include::responses.adoc[]

include::mvc-api.adoc[]
