name: Full Build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java-version: [21]
        include:
          - os: ubuntu-latest
            java-version: 24
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: maven
      - name: Build
        run: mvn -B package -P gradlePlugin
        env:
          BUILD_PORT: 0
          BUILD_SECURE_PORT: 0
          BUILD_LOG_LEVEL: 'ERROR'
      - name: Tests
        uses: mikepenz/action-junit-report@v5
        if: failure()
        with:
          check_name: Test ${{ matrix.os }} ${{ matrix.java-version }} 
          report_paths: '*/target/*/TEST-*.xml'
