name: Full Build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        jre: [21]
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - jre: 24
            os: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.jre }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.jre }}
          distribution: 'temurin'
      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
          enableCrossOsArchive: true
      - name: Install
        run: mvn clean install -DskipTests -q -P gradlePlugin
      - name: Build
        run: mvn clean package -P gradlePlugin
        env:
          BUILD_PORT: 0
          BUILD_SECURE_PORT: 0
          BUILD_LOG_LEVEL: 'ERROR'
      - name: Test Result
        uses: mikepenz/action-junit-report@v5
        if: failure()
        with:
          check_name: JUnit ${{ matrix.kind }} ${{ matrix.jre }} ${{ matrix.os }}
          report_paths: '*/target/*/TEST-*.xml'
